### ISSUE TITLE
1.1.4 Does not roll over at all

### ISSUE THREAD

**Issue by MonkeyBars3k** [lumoe/obsidian-rollover-daily-todos#90] opened 2023-03-11 14:58 UTC
Since the update, Rollover Daily Todos does not roll over my task list at all – it just creates a new Note with the date title and no other content.

macOS/latest Obsidian 1.1.16

**Comment by tim-hilt** [comment] 2023-03-11 18:13
We would need more information in order to help you with this. Which daily notes plugin do you use? What are your settings there? What are your settings for rollover-daily-todos? Have you tried restarting Obsidian? How can I reproduce the issue?

**Comment by MonkeyBars3k** [comment] 2023-03-11 18:26
> We would need more information in order to help you with this. 

Certainly!

> Which daily notes plugin do you use? 

`Daily notes`

> What are your settings there?

`MM-DD-YYYY
paths: default/blank
Open daily note: off`

NB: I did not change any settings before/when this bug started.

> What are your settings for rollover-daily-todos?

`Template heading none
Delete todos off
Remove empty off
Roll over children off`

> Have you tried restarting Obsidian? 

Just did; no change

> How can I reproduce the issue?

I use the `Open today's daily note` link in the left sidebar every day I want a new daily note. After update, the daily note opens without any of the content from the previous note.

**Comment by tim-hilt** [comment] 2023-03-11 19:46
Thanks for the insight! I‘ll see if I can reproduce/debug the issue later today.

if you know how to use npm/pnpm to bundle a project, you could also try debugging this! The code shouldn’t be too complicated :)

**Comment by tim-hilt** [comment] 2023-03-11 20:32
Ah the date-format - I think I did a fix for that, which should already exist on master. You could uninstall the plugin and reinstall from GitHub to fix this.

@lumoe how do you feel about a 1.1.5 release?

**Comment by MonkeyBars3k** [comment] 2023-03-12 14:50
What is this about the date format? I haven't had any issues with it 😌

**Comment by tim-hilt** [comment] 2023-03-12 15:16
In the newer versions I only run the rollover-method on files that are considered daily notes. Before, it was run on every file in the daily notes folder, regardless of the title. And I think I added a bug. So it should still work reliably for the default date-format (yyyy-mm-dd) and should work with your current settings after you update to the master-branch.

**Comment by lumoe** [comment] 2023-03-12 15:57
> Ah the date-format - I think I did a fix for that, which should already exist on master. You could uninstall the plugin and reinstall from GitHub to fix this.
> 
> @lumoe how do you feel about a 1.1.5 release?

I think we already fixed this behaviour with 1.1.4? 
These changes are reflected in https://github.com/lumoe/obsidian-rollover-daily-todos/pull/86 and are released already. 

Do I miss something?

**Comment by tim-hilt** [comment] 2023-03-13 07:36
Oh @lumoe sorry. You’re right.

@MonkeyBars3k I’ll test if I can reproduce

**Comment by lumoe** [comment] 2023-03-13 08:34
@MonkeyBars3k are there any error messages in the Developer Console?

You can open the console by pressing `Ctrl+Shift+i` and navigate to the `Console` tab on the top. 
After opening the Conosle, manually start the roll over process and check if any error messages pop up.

**Comment by MonkeyBars3k** [comment] 2023-03-13 16:27
> @MonkeyBars3k are there any error messages in the Developer Console?
> 
> You can open the console by pressing `Ctrl+Shift+i` and navigate to the `Console` tab on the top. After opening the Conosle, manually start the roll over process and check if any error messages pop up.

cmd+opt-i for mac.

No errors or any other messages pop up in the Console on process run.

**Comment by tim-hilt** [comment] 2023-03-14 06:29
Ok, I just tested it on a new vault and I couldn't reproduce the issue. Here's what I did:

- Match daily notes settings to what @MonkeyBars3k described
- Installed obsidian-rollover-daily-todos (left default settings)
- Added file `03-13-2023` in `/default/blank` with the following content

``` md
- [ ] One checkbox
- [ ] Another checkbox
- [ ] test
```

Then I tested the following interactions:

- Clicking "Open Daily Note" button from the sidebar
- Running "Open todays daily note" from command-palette
- Creating the file manually and running "roll over todos now" from the command-palette

I couldn't reproduce your issue in any of the described ways. Could you maybe provide an example Markdown-file that you can reproduce the issue with @MonkeyBars3k?

**Comment by tim-hilt** [comment] 2023-03-14 22:03
Still can't reproduce unfortunately. I'm out of ideas. Can you try @lumoe ?

**Comment by Shanmukha68** [comment] 2023-03-15 21:20
Me too getting this issue for past 2 weeks. I am using the following date format: YYYY/MMM/DD_ddd in Daily Notes plugin.

**Comment by tim-hilt** [comment] 2023-03-16 05:32
@Shanmukha68 are you using Mac OS too by any chance?

**Comment by Shanmukha68** [comment] 2023-03-16 21:08
@tim-hilt yes, I am using Mac OS.

**Comment by lumoe** [comment] 2023-03-16 21:26
> Still can't reproduce unfortunately. I'm out of ideas. Can you try @lumoe ?

I am not able to reproduce this issue either. Tried it on Ubuntu 20.04 and Android as well.
Unfortunately, I do not have access to a Mac OS machine at the moment to further test things out. 

@Shanmukha68, @MonkeyBars3k depending on your technical knowledge, would it be possible for you to debug the plugin to see on which stage it fails? either through breakpoints in the developer console or cloning the repository?

**Comment by tim-hilt** [comment] 2023-03-16 21:26
I’ll try reproducing it on my Mac then. Thanks for the heads up!

**Comment by tim-hilt** [comment] 2023-03-16 21:50
Still not able to reproduce:

https://user-images.githubusercontent.com/16037579/225759970-e2482cd9-10ae-4c92-9efa-6784b98adfa0.mov

I used @MonkeyBars3k settings for this demonstration. Can you guys try on a new test-vault @MonkeyBars3k @Shanmukha68? If you can't reproduce the issue there, then the issue might be caused by a combination of plugins. In that case I would really appreciate a list of installed plugins. I'll try again basically with a replicated setup then.

**Comment by MonkeyBars3k** [comment] 2023-03-17 15:54
I just did the following and the bug DID reproduce for me:

1. Created new test vault
2. Installed only one community plugin, this one
3. Created a new daily note and changed date title to yesterday
4. Made 4 checkbox items
5. "Open today's daily note" from left bar

Result: note opened with no list beneath date title.

I left the default Core Plugins settings. For me, that means most of them are enabled and the following plugins are **dis**abled:
- Audio recorder
- Format converter
- Publish
- Random note
- Slash commands
- Slides
- Unique note creator
- Workspaces

**Comment by Shanmukha68** [comment] 2023-03-18 00:17
@tim-hilt Please find below the installed plugin list:
ava
better-word-count
calendar
cm-editor-syntax-highlight-obsidian
cmdr
dataview
excalibrain
nldates-obsidian
obsidian-banners
obsidian-book-search-plugin
obsidian-checklist-plugin
obsidian-day-planner
obsidian-dictionary-plugin
obsidian-emoji-toolbar
obsidian-excalidraw-plugin
obsidian-languagetool-plugin
obsidian-plugin-update-tracker
obsidian-rollover-daily-todos
obsidian-tracker
obsidian-zotero-desktop-connector
quickadd
recent-files-obsidian
review-obsidian
settings-search
table-editor-obsidian
templater-obsidian

**Comment by lukeojones** [comment] 2023-03-28 09:35
I had a similar issue on macOS and it spent some time debugging it - in my case it's because the default behaviour for the 'Daily Notes' plugin is to place notes at the root of the vault e.g. the structure looks like:

```
Vault/
├─ 2023-03-27.md
├─ 2023-03-28.md
```

This configuration does not work because the filtering done [here](https://github.com/lumoe/obsidian-rollover-daily-todos/blob/b8ad6b92cc753ddd514a524f0cae10657630249d/src/index.js#L79) is not built to handle files at the root:
```
      .filter((file) =>
        moment(
          file.path.replace(dailyNoteRegexMatch, "$1"),
          format,
          true
        ).isValid()
      )
```

The `file.path.replace(dailyNoteRegexMatch, "$1")` uses `"^" + folder + "/(.*).md$"` which does not match for files in the root. If I have time, it may be worth considering improving this.

But, without a code change, you can do the following to workaround:

1. Create a new folder under root.
2. Change the `Daily Notes` plugin to place notes inside this folder.

```
Vault/
├─ Daily Notes/
│  ├─ 2023-03-27.md
│  ├─ 2023-03-28.md
```

I think this might be why people are struggling to replicate this as they're focusing on the files themselves rather than the location (you'll notice people using this `default/blank` directory structure.

I'm not sure if this is by design or not but if it's a requirement to have this folder structure, the docs could probably make this clearer than they do currently.

**Comment by lukeojones** [comment] 2023-03-28 16:12
No worries. The regex code was changed but not in a way that explains this bug - this might not explain your issue, it just was the solution for mine. Do you keep your daily notes at the root of the vault? If not, then I think you're experiencing something else 😢

**Comment by tim-hilt** [comment] 2023-03-28 18:26
@MonkeyBars3k aaaaaaaah now I understand! Based on the description of your settings I thought your daily notes are in a folder called default/blank 😄 I’ll provide a fix later today.

**Comment by MonkeyBars3k** [comment] 2023-03-28 18:34
Oh my, that is my fault. I meant to say that that field is blank in my settings. Lol who names a folder `blank` though 😆

**Comment by MonkeyBars3k** [comment] 2023-03-28 18:39
Omg that is hilarious 🤦

**Comment by lukeojones** [comment] 2023-03-28 18:44
Haha. Well, glad I could help things along!

Cool plug-in btw.

✌️

**Comment by tim-hilt** [comment] 2023-03-28 18:49
Yes, kudos to you @lukeojones ! Thank you for looking into this!

**Comment by lumoe** [comment] 2023-03-28 21:22
@tim-hilt already created a PR #91 for this issue!

I will give it a final test, if everything works fine we will release 1.1.5. The fix is in `fix/root-daily-folder` - please provide us with feedback if this fixes the issue for you as well. 

Thank @lukeojones for tracking down the issue, I have overlooked this as well :sweat_smile:

**Comment by lumoe** [comment] 2023-03-28 21:33
Checked the behaviour of #91 against 1.1.4 release. I was able to reproduce the issue on 1.1.4 and verify that the fix works.

**Closed** 2023-03-29 05:34 UTC

**Comment by MonkeyBars3k** [comment] 2023-03-29 14:53
Thank you so much lumoe! Plugin updated, fix confirmed working. Well done everyone involved 😌
