### ISSUE TITLE
Rollover interrupts templater commands?

### ISSUE THREAD

**Issue by michaelm2391** [lumoe/obsidian-rollover-daily-todos#104] opened 2023-06-09 21:17 UTC
It seems that I can get Rollover Taily Dodos to work, or Templater, but never both at the same time.

I'm already aware of the issues flagged by the community about the problems with Templater and various workarounds.

However, I think my issue is different: When I trigger the activation of task rollovers with the creation of a new daily note, Templater's commands remain unactioned, and are visible in my daily note as raw code. It seems that the execution of Templater has been interrupted somewhere.

I'm not sure if this is helpful, but my console generated a bunch of errors that look like this:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:138:22)
    at VimrcPlugin.eval (main.ts:127:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:121:2)
    at VimrcPlugin.eval (main.ts:95:9)
    at step (tslib.es6.js:100:23)
```

FYI I'm using (the latest public release of) Rollover Daily Todos, Templater (with 'trigger Templater on new file creation' enabled), and Periodic Notes.

**Comment by tim-hilt** [comment] 2023-06-10 07:12
Duplicate of #63

**Closed by tim-hilt** 2023-06-10 07:12 UTC
