### ISSUE TITLE
Automatic Rollover has racecondition

### ISSUE THREAD

**Issue by MMoMM-org** [lumoe/obsidian-rollover-daily-todos#100] opened 2023-05-15 06:03 UTC
Hi,
I have a template for my daily notes which download information from the internet and asks for 3 values via Templater.

It looks like this causes the tasks to be being deleted but "not" added to the daily note.

I guess they tasks are added to the daily note but due to a racecondition with Templater the document is reverted again.

If I rollover the tasks manually it does work correctly. 

At the moment I can only think about three possible solutions for this:
1. Work together with templater (which has issues on it's own with race conditions) to fix this isse
2. Add an option to not rollover the tasks automatically, only by command
3. Allow a custom delay after creating the daily note to rollover the tasks.

**Comment by tim-hilt** [comment] 2023-05-15 10:36
Duplicate of #63

**Closed by tim-hilt** 2023-05-15 10:36 UTC

**Comment by lumoe** [comment] 2023-09-08 15:36
Hi there,

I've just pushed a new release that introduces the option to disable the automatic rollover when creating the daily file. 

For those utilizing the Templater plugin, ensure you turn off the automatic rollover feature within the *Daily Rollover Settings* tab. You can then manually roll over the to-dos via the provided command.

Currently, this approach ensures optimal compatibility and avoids potential conflicts with the Templater plugin.
