### ISSUE TITLE
[FR] Blacklist / Whitelist characters when rolling over

### ISSUE THREAD

**Issue by SunkSchematic0006** [lumoe/obsidian-rollover-daily-todos#102] opened 2023-05-30 04:35 UTC
Hello, 

With my todo system, I use a variety of characters to determine task status ('?', '/', etc.).

Would it be possible to set it up in such a way that only certain characters aren't rolled over, or in such a way that additional characters are allowed to roll over?

Thank you for your time!

**Comment by tim-hilt** [comment] 2023-05-30 05:09
Duplicate of #87

**Closed by tim-hilt** 2023-05-30 05:09 UTC

**Comment by tim-hilt** [comment] 2023-05-30 05:11
Hey @SunkSchematic0006 and thanks for opening an issue! It might be a pleasant surprise, that this issue is not only on our radar, but there’s already a PR open that will add this functionality. Take a look at #76.

@lumoe do you think merging this PR would be a bad idea? Did I miss anything?
