### ISSUE TITLE
Unfinished todo's are no longer rolled over

### ISSUE THREAD

**Issue by talios** [lumoe/obsidian-rollover-daily-todos#84] opened 2023-01-26 09:16 UTC
Coming out of testing #41 - I'm finding for my install, I'm no longer seeing any TOODs being rolled over.

From the testing of the above issue, I deleted the `obsidian-rollover-daily-todo` directory from my `Documents/Obsidian/.obsidian/plugins` folder, and cloned the upstream repository and built commit `a4d090eb7facb6`:

```
$ git clone git@github.com:lumoe/obsidian-rollover-daily-todos.git
$ cd obsidian-rollover-daily-todos
$ pnpm install
$ pnpm build
```

The `README.md` file doesn't include any specific instructions for building, but based on the ci workflow in `.github/workflows/ci.yml` I settled on the above `pnpm` calls.

My daily note format is: `YYYY/gggg-[W]ww/YYYY-MM-DD` and I have all three roll-over config options enabled.

I'm not seeing any errors in the dev-console inside Obsidian at all.

**Comment by tim-hilt** [comment] 2023-01-26 10:36
Thanks for reporting this issue! Do you use periodic notes or the daily notes plugin? Did you try restarting obsidian and tried it afterwards?

**Comment by talios** [comment] 2023-01-26 20:30
Using Periodic Notes.   Daily Notes is disabled.

**Comment by talios** [comment] 2023-02-06 06:23
Was there any progress on this? Or anything I can try to see what's happening (or not happening).

With the dev tools open and running "Rollover Todos Now" I see nothing in the console.

**Comment by tim-hilt** [comment] 2023-02-07 21:52
can you share your settings for periodic notes? I'm working on a fix for the master-branch. The issue was caused by using nested folders as the format-specifier. Maybe you use something like `YYYY/YYYY-MM-DD` as your format?

**Comment by tim-hilt** [comment] 2023-02-07 22:09
update: also pushed the bugfix to the release-2.0 branch. Can you test once again?

**Comment by talios** [comment] 2023-02-08 23:45
Settings:

Format: YYYY/gggg-[W]ww/YYYY-MM-DD
Template: Templates/Daily Note Template
Folder: Daily Notes


Updated to the `release-2.0` branch:

- TODOs with `[ ]` did roll over, however, any with the newly supported 'in-progress' type values did not, such as `[/]` or `[?]` - maybe we want to roll over things that are NOT `[x]` rather than those that ARE `[ ]`?
- TODOs rolled over to the END of the daily note, not into my "Things to Try to Get Done" heading, looking at the configuration I see I no longer have any headings configured, or an ability to do so: 
![image](https://user-images.githubusercontent.com/19093/217677150-301f78f4-1fc5-4118-999f-90880e9da9da.png)

**Comment by tim-hilt** [comment] 2023-02-09 05:34
> the newly supported 'in-progress' type values

i think the PR for this is still open, so the functionality is not yet available.

> looking at the configuration I see I no longer have any headings

loading of the headings is not 100% reliable for me. Could you check if the headings appear after you deactivate and reactivate obsidian-rollover-todos?

**Comment by talios** [comment] 2023-02-09 06:02
Deactivating/Reactivating the plugin didn't help with the headers (pulled the latest changes in the release branch).

Interesting - now when I manually roll over when I have my current days notes:

![image](https://user-images.githubusercontent.com/19093/217731051-6e206f47-e56b-430e-af75-3683d41cacbf.png)

**Comment by talios** [comment] 2023-02-09 06:27
Switched to the `fix/complex-date-formats` branch and rebuilt - the plugin now finds my headings, and finds the todos to move over, and moves over the `[ ]` items only (so not the in-progress items I mentioned earlier).

**Comment by tim-hilt** [comment] 2023-02-09 07:57
just to summarize, so that things are not getting mixed up: `fix/complex-date-formats` still shows the headers as a dropdown. The "new" header-parsing is only available on `release-2.0`. Both branches have the fix for handling complex dates in place.

If you see your todos rolled over on both branches, then this issue should be closed.

I had another look in the code. On `release-2.0`-branch, the settings for the `periodic-notes`-plugin are not respected; I have to add that back.

Can you open a new issue for respecting periodic-notes in the `release-2.0`-branch? Please prefix the issue with `v2: ` or something along these lines. This would make my life a bit easier.

**Comment by tim-hilt** [comment] 2023-02-09 08:16
Update: 3676645214aff231318f3f9bf195cc0471441f67 adds support for periodic-notes back on branch release-2.0. If you could test and confirm that it works, we can work around creating a new issue.

**Comment by talios** [comment] 2023-02-09 10:08
I just pulled the `release-2.0` branch and rebuilt:

 - once again "2023-02-09 is not a daily note"
 - headers are not shown in the config

Switched back to `fix/complex-date-formats` and pulled Lukas Mölschl's commit 72d854940f594d - and that does as expected.

I see the two branches differ quite a bit with dependencies.

I wonder if there's something else missing on that branch - tripping up the headers?

**Comment by talios** [comment] 2023-02-09 10:18
I just tried the `master` branch (2ec2494f934868) - that works fine for rolling over, showing the headers, and everything.

I also raised #87 to cover the `[/]` style TODO entries I mentioned earlier.

**Comment by tim-hilt** [comment] 2023-02-09 10:49
> once again "2023-02-09 is not a daily note"

did you create the new note as `Daily Notes/2023/2023-W06/2023-02-09.md`?

> headers are not shown in the config

can you maybe share `Templates/Daily Note Template`? I can't reproduce the headers not showing up.

> I wonder if there's something else missing on that branch - tripping up the headers?

I don't think that that's the cause of the error. The template-headings are parsed by obsidian-rollover-todos without using any dependencies.

**Comment by tim-hilt** [comment] 2023-02-15 06:55
Can you comment on this? I implemented a fix and am very interested to know if it works for you.

with no feedback I‘d consider this issue resolved.

**Comment by VOOM108** [comment] 2023-02-21 20:19
I am not sure, if I get everything with the testing of the 2.0-branch. I installed it just now after the 1.1.4 in Obsidian did not show any options any more, just empty. 

Now I have the options page again, but on top there are no headers shown. I have a template for daily notes set up and there are headers in that template. 

I still have to see, if the open tasks are rolled over with the next note....

**Comment by tim-hilt** [comment] 2023-02-21 20:41
Can you restart Obsidian and look into rollover-daily-todos settings again? Maybe try with activating/deactivating. If that doesn’t work we have to look at how you installed from the release-2.0 branch.

**Comment by VOOM108** [comment] 2023-02-21 21:07
Neither restarting nor off and on did sth. 

I cloned the repo with argument release-2.0 to the plugins folder (git bash), then in the subfolder via powershell (git win would not recognize pnpm command): 

pnpm install
pnpm build

**Comment by talios** [comment] 2023-02-21 21:23
@VOOM108 sounds like the same issues I had when trying the release-2.0 branch awhile ago.

**Comment by VOOM108** [comment] 2023-02-22 01:10
Rolling over yesterday's tasks did not work, either...

**Comment by tim-hilt** [comment] 2023-02-23 10:30
I would have been very surprised if that worked, given the information that you provided earlier!

I did find two bugs when inspecting this problem though. The bugs are fixed in the release-2.0-branch. Can you

``` sh
git pull && pnpm clean && pnpm build
```

again and see if that fixed the issue? @talios it would be very helpful if you could do the same thing!

**Comment by talios** [comment] 2023-02-23 21:44
```
$ git pull && pnpm clean && pnpm build

Already up to date.

> obsidian-rollover-daily-todos@1.1.3 clean /Users/amrk/Documents/Obsidian/.obsidian/plugins/obsidian-rollover-daily-todos
> rimraf main.js data.json

sh: rimraf: command not found
```

Whats `rimraf`? I tried doing a `pnpm install` but that didn't help.

**Comment by talios** [comment] 2023-02-23 21:47
Manually running `pnpm install rimraf` resolved that issue - now to test.

I now see my template headings which is a good sign.  Will do some testing shortly.

**Comment by tim-hilt** [comment] 2023-02-23 23:27
Ah yes sorry, I forgot about pnpm install.

Thanks for confirming that it works again!

**Comment by talios** [comment] 2023-02-23 23:27
That seems to work be working when I manually run "roll over todays now" on an existing daily-todo note doesn't seem to run when creating the new daily note (altho, I had deleted the note, not sure if theres state tracking there ).

I've noticed however, occasionally, after the pulled in notes I end up with my title as a note entry:

```
## Things to Try to Get Done

 - [ ] we pulled this over
 - [ ] and this

 - Things to do today
```

**Closed by tim-hilt** 2023-02-23 23:27 UTC

**Comment by tim-hilt** [comment] 2023-02-24 00:01
If I understood correctly

1. Automatic rollover doesn’t seem to work for you
2. Unexpected lines end up in your note after rollover. 

Is that right so far?
Can you provide reproduction steps for both cases?

**Comment by talios** [comment] 2023-02-24 00:10
Further testing:

1. automatic rollover IS working - strangely it didn't earlier, but now consistently does
2. Seems I'd added that as a place holder in my daily note template - removing that and every is GOOD AS GOOD!

Cheers
